FROM python:3.9.1-buster

LABEL "maintainer"="brendenahyde@gmail.com"

USER root

ENV GIT_USER="Dude Dudeman"
ENV GIT_EMAIL="dudedudeman@gmail.com"
ENV GITHUB_TOKEN="12345671324891asdjbfblkj27123"
ENV GITHUB_GNUCASH_URL="https://github.com/dudedudeman/gnucash-budget.git"
ENV CLONE_URL="https://12345671324891asdjbfblkj27123@github.com/dudedudeman/gnucash-budget.git"
ENV GNUCASH_BOOK_NAME="gnucash-budget.gnucash"
ENV GNUCASH_DIR="/gnucash-budget"

RUN apt-get update
RUN apt-get install -y git gnucash python3-pip

RUN ["/bin/bash", "-c", "git clone $CLONE_URL"]

RUN mkdir /GnuCash-Helper
WORKDIR /GnuCash-Helper
ADD requirements.txt requirements.txt
ADD gnucash_helper.py gnucash_helper.py
ADD app.py app.py
COPY templates/ templates/

RUN pip3 install -r requirements.txt
EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "--worker-tmp-dir", "/dev/shm", "app:app"]
